workspace:
  base: /drone
  path: src/github.com/vmware/vic-tools

clone:
  git:
    image: plugins/git
    tags: true
    recursive: false

pipeline:
  check-org-membership:
    image: 'wdc-harbor-ci.eng.vmware.com/default-project/vic-integration-test:1.48'
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
    secrets:
      - github_automation_api_key
      - skip_check_membership
    commands:
      - echo ${DRONE_COMMIT_AUTHOR}
      - echo $SKIP_CHECK_MEMBERSHIP
      - if [ "$SKIP_CHECK_MEMBERSHIP" = "true" ]; then echo 'check-org-membership step skipped'; else /bin/bash -c '[[ ! $(curl --silent "https://api.github.com/orgs/vmware/members/${DRONE_COMMIT_AUTHOR}?access_token=$GITHUB_AUTOMATION_API_KEY") ]]'; fi
    when:
      status: success

  vic-tools:
    image: 'wdc-harbor-ci.eng.vmware.com/default-project/vic-integration-test:1.48'
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
    commands:
      - make all
    when:
      status: success

  notify-slack:
    image: plugins/slack
    secrets:
      - source: slack_url
        target: slack_webhook
    username: drone
    template: >
      build https://ci-vic.vmware.com/vmware/vic-tools/{{ build.number }} finished with a {{ build.status }} status.
    when:
      repo: vmware/vic-tools
      event: [push, tag]
      status: [success, failure]
